// data.js
// WEIGHTS: 1 = Light (1 day), 2 = Medium (2-3 days), 3 = Heavy (3-5 days)

const SYLLABUS = {
    "Ancient & Medieval History": [
        {t: "Indus Valley Civilization", w: 2}, 
        {t: "Vedic Civilization", w: 2}, 
        {t: "Jainism and Buddhism", w: 3},
        {t: "Mahajanapadas", w: 1}, 
        {t: "Mauryan Empire", w: 3}, 
        {t: "Post Mauryan Period", w: 2},
        {t: "Gupta Empire", w: 3}, 
        {t: "Post Gupta Period", w: 2}, 
        {t: "Tripartite Conflict", w: 1},
        {t: "Rashtrakutas", w: 1}, 
        {t: "Palas of Bengal", w: 1}, 
        {t: "Chalukyas", w: 2},
        {t: "Cholas", w: 2}, 
        {t: "Pallavas", w: 1}
    ],
    "Medieval & Modern History": [
        {t: "Muslim Invasion", w: 1}, 
        {t: "Slave Dynasty", w: 2}, 
        {t: "Khilji Dynasty", w: 2},
        {t: "Tughlaq Dynasty", w: 2}, 
        {t: "Sayyed and Lodi", w: 1}, 
        {t: "Vijayanagar Kingdom", w: 2},
        {t: "Bahmani Kingdom", w: 1}, 
        {t: "Mughal Administration", w: 3}, 
        {t: "Babur", w: 1},
        {t: "Humayun", w: 1}, 
        {t: "Suri Dynasty", w: 1}, 
        {t: "Akbar", w: 3}, 
        {t: "Jahangir", w: 2},
        {t: "Shah Jahan", w: 2}, 
        {t: "Aurangzeb", w: 2}, 
        {t: "Mughal Arts/Culture", w: 3},
        {t: "Mughal Economy", w: 2}, 
        {t: "Marathas", w: 3}, 
        {t: "Sikhs", w: 2}
    ],
    "Indian Polity": [
        {t: "DPSP", w: 3}, 
        {t: "Fundamental Rights", w: 3}, 
        {t: "President", w: 2},
        {t: "Vice President", w: 1}, 
        {t: "Prime Minister", w: 2}, 
        {t: "Rajya Sabha", w: 2},
        {t: "Lok Sabha", w: 2}, 
        {t: "Powers of Parliament", w: 3}, 
        {t: "Citizenship", w: 1},
        {t: "Supreme Court", w: 3}, 
        {t: "High Court", w: 2}, 
        {t: "Preamble", w: 1},
        {t: "Centre-State Relations", w: 3}, 
        {t: "Amendments", w: 3},
        {t: "Constitutional History", w: 2}, 
        {t: "Constituent Assembly", w: 1}, 
        {t: "UPSC", w: 1},
        {t: "Election Commission", w: 2}, 
        {t: "Human Rights Comm", w: 1}, 
        {t: "Lokpal", w: 1},
        {t: "CVC & RTI", w: 1}, 
        {t: "Finance Commission", w: 2}, 
        {t: "NITI Aayog", w: 2}, 
        {t: "Governor", w: 2},
        {t: "CM & Council", w: 2}, 
        {t: "State Legislature", w: 2}, 
        {t: "Local Govt", w: 3}
    ],
    "Indian Geography": [
        {t: "Basics of India", w: 1}, 
        {t: "Himalayas", w: 3}, 
        {t: "Northern Plains", w: 2},
        {t: "Deserts", w: 1}, 
        {t: "Coastal Plains", w: 1}, 
        {t: "Plateaus", w: 2},
        {t: "Central Highlands", w: 1}, 
        {t: "Ghats", w: 2}, 
        {t: "Islands", w: 1},
        {t: "Ganga System", w: 3}, 
        {t: "Indus System", w: 2}, 
        {t: "Brahmaputra System", w: 2},
        {t: "East Flowing Rivers", w: 2}, 
        {t: "West Flowing Rivers", w: 2}, 
        {t: "Waterfalls/Lakes", w: 1},
        {t: "Energy Resources", w: 2}, 
        {t: "Minerals (Iron/Gold)", w: 2}, 
        {t: "Industries", w: 2},
        {t: "Soils", w: 3}, 
        {t: "Climate/Monsoon", w: 3}, 
        {t: "Agriculture", w: 3},
        {t: "Population", w: 2}, 
        {t: "Forests", w: 2}, 
        {t: "National Parks", w: 2},
        {t: "Transport", w: 2}
    ]
};